export const LACINK = {
    title: "Bielaruski techničny pieraklad",
    glossary: "Hliasaryj",
    rules: "Pravily",
    links: "Spasylki",
    pg: "st. ",
    z: " z ",
    input_eng_term: "uviadzicie anh. termin",
    back: "Nazad",
    term: "Termin",
    wrong_usage: "Niapraviĺnaje ŭzyvańnie",
    comment: "Kamentar",
    narkam: "be",
    tarask: "be@tarask",
    lacink: "be@latin",
    a_dictionary: "Hliasaryj pierakladčykaŭ Ubuntu",
    b_dictionary: "Terminy Proton. Košaĺ i Turok",
    c_dictionary: "Sloŭnik Puhačova",
    d_dictionary: "Koliery",
    e_dictionary: "Sloŭnik Skalkoviča",
};