export const NARKAM = {
    title: "Беларускі тэхнічны пераклад",
    glossary: "Гласарый",
    rules: "Правілы",
    links: "Спасылкі",
    pg: "ст. ",
    z: " з ",
    input_eng_term: "увядзіце анг. тэрмін",
    back: "Назад",
    term: "Тэрмін",
    wrong_usage: "Няправільнае ўжыванне",
    comment: "Каментарый",
    narkam: "be",
    tarask: "be@tarask",
    lacink: "be@latin",
    a_dictionary: "Гласарый перакладчыкаў Ubuntu",
    b_dictionary: "Тэрміны Proton. Кошаль і Турок",
    c_dictionary: "Слоўнік Пугачова",
};