export const TARASK = {
    title: "Беларускі тэхнічны пераклад",
    glossary: "Глясарый",
    rules: "Правілы",
    links: "Спасылкі",
    pg: "ст. ",
    z: " з ",
    input_eng_term: "увядзіце анг. тэрмін",
    back: "Назад",
    term: "Тэрмін",
    wrong_usage: "Няправільнае ўжываньне",
    comment: "Камэнтар",
    narkam: "be",
    tarask: "be@tarask",
    lacink: "be@latin",
    a_dictionary: "Глясарый перакладчыкаў Ubuntu",
    b_dictionary: "Тэрміны Proton. Кошаль і Турок",
    c_dictionary: "Слоўнік Пугачова",
    d_dictionary: "Колеры",
    e_dictionary: "Слоўнік Скалковіча",
};